import { sendMail } from "../utils/sendMail.js";

export const createInternApplication = async (req, res) => {
  try {
    console.log("📩 Intern application received:", req.body);

    const {
      fullName,
      email,
      phone,
      degree,
      graduationYear,
      location,
      role,
      resume,
    } = req.body;

    if (!resume) {
      return res.status(400).json({ message: "Resume file ID missing!" });
    }

    // Google Drive Link
    const resumeUrl = `https://drive.google.com/file/d/${resume}/view`;

    // -----------------------------------------------
    // HR + ADMIN EMAIL HTML
    // -----------------------------------------------
  const hrHtml = `
  <div style="
      font-family: 'Segoe UI', Arial, sans-serif;
      max-width: 650px;
      margin: auto;
      background: #ffffff;
      padding: 35px;
      border-radius: 12px;
      border: 1px solid #e5e7eb;
      box-shadow: 0 4px 25px rgba(0,0,0,0.06);
  ">

    <!-- HEADER -->
    <div style="text-align: center; margin-bottom: 25px;">
      <h1 style="color:#0c3b70; margin: 0; font-size: 26px;">
        Internship Application Received
      </h1>
      <p style="color:#555; font-size: 14px; margin-top: 6px;">
        A new candidate has applied for the internship program.
      </p>
    </div>

    <!-- PROFILE BOX -->
    <div style="
      background: #f7faff;
      padding: 20px;
      border-left: 4px solid #0c3b70;
      border-radius: 10px;
      margin-bottom: 25px;
    ">
      <h2 style="margin: 0; color:#0c3b70; font-size: 20px;">
        Applicant Details
      </h2>

      <p style="margin: 10px 0 0;"><strong>Name:</strong> ${fullName}</p>
      <p style="margin: 6px 0;"><strong>Email:</strong> ${email}</p>
      <p style="margin: 6px 0;"><strong>Phone:</strong> ${phone}</p>
      <p style="margin: 6px 0;"><strong>Degree:</strong> ${degree}</p>
      <p style="margin: 6px 0;"><strong>Graduation Year:</strong> ${graduationYear}</p>
      <p style="margin: 6px 0;"><strong>Location:</strong> ${location}</p>
      <p style="margin: 6px 0;"><strong>Role Applied:</strong> ${role}</p>
    </div>

    <!-- RESUME BUTTON -->
    <div style="text-align: center; margin-top: 25px;">
      <a href="${resumeUrl}" target="_blank"
        style="
          background:#0c3b70;
          color:white;
          padding:12px 22px;
          font-size:15px;
          border-radius:8px;
          text-decoration:none;
          font-weight:600;
          display:inline-block;
          box-shadow:0 3px 8px rgba(0,0,0,0.15);
        ">
        📎 View Resume
      </a>
    </div>

    <!-- FOOTER -->
    <hr style="margin: 30px 0; border:none; border-top:1px solid #ddd;" />

    <div style="text-align:center; font-size: 13px; color:#777;">
      <p style="margin: 0;">
        This email was automatically generated by 
        <strong>Aryahs World Infotech</strong>.
      </p>
      <p style="margin: 5px 0 0;">Applicant activity log has been updated.</p>
    </div>

  </div>
`;


    // -----------------------------------------------
    // SEND TO HR
    // -----------------------------------------------
    await sendMail({
      to: "hr@aryahsworld.com",
      subject: `New Internship Application - ${fullName}`,
      html: hrHtml,
    });

    // -----------------------------------------------
    // SEND TO ADMIN
    // -----------------------------------------------
    await sendMail({
      to: "tech.aryahs@gmail.com",
      subject: `Admin Copy - ${fullName}`,
      html: hrHtml,
    });

    // -----------------------------------------------
    // APPLICANT AUTO-REPLY EMAIL WITH SOCIAL LINKS
    // -----------------------------------------------
    await sendMail({
      to: email,
      subject: "Your Internship Application Has Been Received",
      html: `
        <div style="font-family: Arial; padding: 20px;">
          <h2 style="color:#0c3b70;">Application Received</h2>

          <p>Hello <strong>${fullName}</strong>,</p>
          <p>Thank you for applying for an internship at 
             <strong>Aryahs World Infotech</strong>.</p>

          <p>Your application for the role of 
             <strong>${role}</strong> has been successfully received.</p>

          <p>Our HR team will review your profile and contact you 
             if you are shortlisted.</p>

          <br/>

          <h3 style="color:#0c3b70;">Stay Connected</h3>

          <p>You can explore more about us here:</p>

          <p>
            🌐 <a href="https://www.aryahsworld.com/" target="_blank" style="color:#0c3b70;">
              Visit our Website
            </a>
          </p>

          <p>
            💼 <a href="https://www.linkedin.com/company/aryahs-world-infotech" 
                target="_blank" style="color:#0c3b70;">
              Connect on LinkedIn
            </a>
          </p>

          <p>
            📸 <a href="https://www.instagram.com/aryahsworldinfotech?igsh=Y3Fudzkyd3ZsMGNi" 
                target="_blank" style="color:#0c3b70;">
              Follow us on Instagram
            </a>
          </p>

          <br/>

          <p>
            Best Regards,<br/>
            <strong>Aryahs World Infotech</strong>
          </p>

          <hr style="margin-top:20px;"/>

          <p style="font-size: 12px; color: #666;">
            This is an automated email. Please do not reply.
          </p>
        </div>
      `,
    });

    res.status(200).json({
      success: true,
      message: "Application submitted successfully!",
    });

  } catch (error) {
    console.error("❌ Error:", error);
    res.status(500).json({
      success: false,
      message: "Server error",
      error: error.message,
    });
  }
};
